%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%FUNCTION EVALUATING THE EQUATION (2.15) IN THE THESIS OF FREDERICK
%GOSSELIN. 
%THIS EQUATION COUPLES A EULER-BERNOULLI BEAM FORMULATION WITH AN EMPIRICAL
%DRAG FORMULATION.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function answer=beamwithdrag(s,theta,CYCD,beta);
% THE SCALAR s IS THE LAGRANGIAN COORDINATE MEASURED ALONG THE BEAM
% THE ARRAY theta IS THE LOCAL MEASURE OF THE ANGLE BETWEEN THE DIRECTION
% OF THE FLOW AND THE TANGENT TO THE BEAM ALONG WITH ITS FIRST AND SECOND
% DERIVATIVES WITH RESPECT TO s.
% THE SCALAR CYCD IS THE VALUE OF THE SCALED CAUCHY NUMBER
% THE SCALAR beta IS THE TAPERING RATIO OF THE BEAM

clear answer
%FIRST DERIVATIVE OF THETA WITH RESPECT TO s
answer(1,1)=theta(2);
%SECOND DERIVATIVE OF THETA WITH RESPECT TO s
answer(2,1)=theta(3);
%THIRD DERIVATIVE OF THETA WITH RESPECT TO s
answer(3,1)=-CYCD/beta*sin(theta(1))^2+2*(1-beta)/(1-(1-beta)*s)*theta(3);
return
